import type { ProposalPlugin } from "../core/plugin-manager";
import type { ProposalContext } from "../core/types";
import modelRouter from "../core/model-router";

export const ProposalGeneratorPlugin: ProposalPlugin = {
  id: "proposal-generator",
  name: "AI Proposal Generator",
  version: "1.0.0",
  stage: "reason",
  enabled: true,
  priority: 50,

  async run(context: ProposalContext): Promise<ProposalContext> {
    console.log("[ProposalGenerator] Generating proposal content...");

    const { merchantData, enrichedData, salesperson, pricingData } = context;

    const prompt = `Generate a professional, persuasive proposal for:

MERCHANT INFORMATION:
- Business: ${merchantData.businessName}
- Owner: ${merchantData.ownerName || "Business Owner"}
- Industry: ${merchantData.industry || "Retail/Service"}
${merchantData.address ? `- Location: ${merchantData.address}` : ""}
${merchantData.monthlyVolume ? `- Monthly Volume: $${merchantData.monthlyVolume.toLocaleString()}` : ""}
${merchantData.averageTicket ? `- Average Ticket: $${merchantData.averageTicket}` : ""}

${enrichedData.businessDescription ? `BUSINESS DESCRIPTION:\n${enrichedData.businessDescription}\n` : ""}
${enrichedData.services?.length ? `SERVICES: ${enrichedData.services.join(", ")}\n` : ""}

SALES REP:
- Name: ${salesperson.name}
- Title: ${salesperson.title || "Account Executive"}

REP NOTES:
${merchantData.repNotes || "None provided"}

Generate a proposal with these sections:
1. Executive Summary (personalized to their business)
2. Current State Analysis (pain points in payment processing)
3. Proposed Solution (Dual Pricing or Interchange Plus recommendation)
4. Projected Savings (conservative estimates)
5. Why PCBancard (value proposition)
6. Next Steps

Return as JSON:
{
  "executiveSummary": "...",
  "currentState": "...",
  "proposedSolution": "...",
  "projectedSavings": "...",
  "whyPCBancard": "...",
  "nextSteps": "...",
  "personalizedHook": "one sentence that shows we understand their business"
}`;

    try {
      const aiResponse = await modelRouter.route({
        type: "writing",
        prompt,
        systemPrompt: `You are an expert sales proposal writer for PCBancard, a payment processing company. 
Write persuasive, professional content that addresses specific merchant pain points.
Always recommend Dual Pricing as the primary solution for maximum savings.
Be specific about benefits, not generic.`
      });

      const jsonMatch = aiResponse.content.match(/\{[\s\S]*\}/);
      if (jsonMatch) {
        const proposal = JSON.parse(jsonMatch[0]);
        
        (context as any).proposalContent = proposal;
        
        context.audit.push({
          timestamp: new Date(),
          stage: "reason",
          plugin: this.id,
          model: aiResponse.model,
          action: "Proposal content generated",
          duration: aiResponse.latencyMs,
          success: true,
          metadata: {
            sectionsGenerated: Object.keys(proposal).length,
            tokensUsed: aiResponse.tokensUsed
          }
        });

        context.citations.push({
          source: "AI Generation",
          reference: `Generated by ${aiResponse.model}`,
          confidence: 0.9
        });
      }

      console.log("[ProposalGenerator] Proposal content generated successfully");

    } catch (error) {
      console.error("[ProposalGenerator] Error:", error);
      context.errors.push(`Proposal generation failed: ${error instanceof Error ? error.message : "Unknown error"}`);
    }

    return context;
  }
};

export default ProposalGeneratorPlugin;
