import type { ProposalPlugin } from "../core/plugin-manager";
import type { ProposalContext } from "../core/types";
import modelRouter from "../core/model-router";

export const ProposalGeneratorPlugin: ProposalPlugin = {
  id: "proposal-generator",
  name: "AI Proposal Generator",
  version: "1.0.0",
  stage: "reason",
  enabled: true,
  priority: 50,

  async run(context: ProposalContext): Promise<ProposalContext> {
    console.log("[ProposalGenerator] Generating proposal content...");

    const { merchantData, enrichedData, salesperson, pricingData } = context;
    const interchangeCalc = (context as any).interchangeCalculation;
    const savingsAnalysis = (context as any).savingsAnalysis;

    const interchangeContext = interchangeCalc ? `
INTERCHANGE ANALYSIS (Calculated from official card brand rate tables):
- Monthly Processing Volume: $${interchangeCalc.monthlyVolume.toLocaleString()}
- Average Transaction: $${interchangeCalc.averageTicket}
- Estimated Transactions/Month: ${interchangeCalc.transactionCount}
- Current Effective Rate: ${savingsAnalysis?.currentEffectiveRate || interchangeCalc.effectiveRate}%
- Wholesale Interchange Cost: $${interchangeCalc.totalWholesaleCost.toLocaleString()}/month

CARD BRAND BREAKDOWN:
- Visa: $${interchangeCalc.breakdown.visa.cost} (${interchangeCalc.breakdown.visa.rate}% avg)
- Mastercard: $${interchangeCalc.breakdown.mastercard.cost} (${interchangeCalc.breakdown.mastercard.rate}% avg)
- Discover: $${interchangeCalc.breakdown.discover.cost} (${interchangeCalc.breakdown.discover.rate}% avg)
- Amex: $${interchangeCalc.breakdown.amex.cost} (${interchangeCalc.breakdown.amex.rate}% avg)
- Debit: $${interchangeCalc.breakdown.debit.cost} (${interchangeCalc.breakdown.debit.rate}% avg)

DUAL PRICING SAVINGS OPPORTUNITY:
- Service Fee Collection (3.5%): $${interchangeCalc.dualPricingSavings.serviceFeeCollected}/month
- Net Cost to Merchant: $${interchangeCalc.dualPricingSavings.netCostToMerchant}/month
- ANNUAL SAVINGS: $${interchangeCalc.dualPricingSavings.annualSavings}
` : "";

    const prompt = `Generate a professional, persuasive proposal for:

MERCHANT INFORMATION:
- Business: ${merchantData.businessName}
- Owner: ${merchantData.ownerName || "Business Owner"}
- Industry: ${merchantData.industry || "Retail/Service"}
${merchantData.address ? `- Location: ${merchantData.address}` : ""}
${merchantData.monthlyVolume ? `- Monthly Volume: $${merchantData.monthlyVolume.toLocaleString()}` : ""}
${merchantData.averageTicket ? `- Average Ticket: $${merchantData.averageTicket}` : ""}
${interchangeContext}
${enrichedData.businessDescription ? `BUSINESS DESCRIPTION:\n${enrichedData.businessDescription}\n` : ""}
${enrichedData.services?.length ? `SERVICES: ${enrichedData.services.join(", ")}\n` : ""}

SALES REP:
- Name: ${salesperson.name}
- Title: ${salesperson.title || "Account Executive"}

REP NOTES:
${merchantData.repNotes || "None provided"}

Generate a proposal with these sections. Use the EXACT savings numbers provided above:
1. Executive Summary (personalized to their business, mention specific annual savings)
2. Current State Analysis (pain points in payment processing, current effective rate)
3. Proposed Solution (Dual Pricing recommendation with how it works)
4. Projected Savings (use the EXACT numbers from interchange analysis above)
5. Why PCBancard (value proposition - local support, no hidden fees, free equipment)
6. Next Steps (clear call to action)

Return as JSON:
{
  "executiveSummary": "...",
  "currentState": "...",
  "proposedSolution": "...",
  "projectedSavings": "...",
  "whyPCBancard": "...",
  "nextSteps": "...",
  "personalizedHook": "one sentence that shows we understand their business"
}`;

    try {
      const aiResponse = await modelRouter.route({
        type: "writing",
        prompt,
        systemPrompt: `You are an expert sales proposal writer for PCBancard, a payment processing company. 
Write persuasive, professional content that addresses specific merchant pain points.
Always recommend Dual Pricing as the primary solution for maximum savings.
Be specific about benefits, not generic.`
      });

      const jsonMatch = aiResponse.content.match(/\{[\s\S]*\}/);
      if (jsonMatch) {
        const proposal = JSON.parse(jsonMatch[0]);
        
        (context as any).proposalContent = proposal;
        
        context.audit.push({
          timestamp: new Date(),
          stage: "reason",
          plugin: this.id,
          model: aiResponse.model,
          action: "Proposal content generated",
          duration: aiResponse.latencyMs,
          success: true,
          metadata: {
            sectionsGenerated: Object.keys(proposal).length,
            tokensUsed: aiResponse.tokensUsed
          }
        });

        context.citations.push({
          source: "AI Generation",
          reference: `Generated by ${aiResponse.model}`,
          confidence: 0.9
        });
      }

      console.log("[ProposalGenerator] Proposal content generated successfully");

    } catch (error) {
      console.error("[ProposalGenerator] Error:", error);
      context.errors.push(`Proposal generation failed: ${error instanceof Error ? error.message : "Unknown error"}`);
    }

    return context;
  }
};

export default ProposalGeneratorPlugin;
